#!/usr/bin/env bash
#A script that implements the if, elif, and else condition inside a while loop

i=1
while ((i<=10))
do
	if ((i == 4));
	then
		echo "bad luck"
	elif ((i == 8));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	((i++))
done
