#!/usr/bin/env bash
# A script that displays the content of the current directory in a list format
# Only the part of the name after the first dash is displayed

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        name_part=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_part"
    fi
done
